# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/kerneltoast/android_kernel_google_zuma
          kernel-branch: 15.0.0-sultan
          config: zuma_defconfig
          arch: arm64
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/7775eb113f960bc69a780b621d03a715914d4bca.tar.gz
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-cmd: "-j$(nproc)"
