name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/kerneltoast/android_kernel_google_zuma
          kernel-branch: 15.0.0-sultan
          config: zuma_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r530567
