name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Nom du kernel'
        required: true
        default: 'AutoSult'

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    env:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}

    steps:
      # Étape 1: Cloner le dépôt du kernel à la racine
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          repository: kerneltoast/android_kernel_google_zuma
          ref: 15.0.0-sultan
          path: .  # Cloner directement à la racine du répertoire de travail

      # Étape 2: Vérifier le contenu du répertoire après le clonage
      - name: List Kernel Directory
        run: ls -la

      # Étape 3: Modifier la version du kernel dans le defconfig
      - name: Modify kernel version
        run: |
          echo 'CONFIG_LOCALVERSION="-${{ env.KERNEL_NAME }}"' >> arch/arm64/configs/zuma_defconfig

      # Étape 4: Modifier le fichier Makefile pour changer l'EXTRAVERSION
      - name: Modify Makefile EXTRAVERSION
        run: |
          sed -i 's/^EXTRAVERSION =.*/EXTRAVERSION = -${{ env.KERNEL_NAME }}/' Makefile

      # Étape 5: Vérifier le contenu du répertoire avant de lancer la compilation
      - name: List Kernel Directory Before Build
        run: ls -la

      # Étape 6: Construire le kernel
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-dir: .  # Utiliser le répertoire courant comme répertoire du kernel
          config: zuma_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/7775eb113f960bc69a780b621d03a715914d4bca.tar.gz
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
